apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-data-cm
  namespace: ldap
data:
  custom.ldif: |
    dn: ou=groups,dc=hashibank,dc=com
    objectClass: organizationalunit
    objectClass: top
    ou: groups
    description: groups of users

    dn: ou=users,dc=hashibank,dc=com
    objectClass: organizationalunit
    objectClass: top
    ou: users
    description: users
