defaultVaultConnection:
  enabled: true
  address: "https://vault-active.primary-vault.svc.cluster.local:8200"
  skipTLSVerify: true
controller:
  manager:
    clientCache:
      persistenceModel: direct-encrypted
      storageEncryption:
        enabled: false
        mount: demo-auth-mount
        keyName: vso-client-cache
        transitMount: demo-transit
        kubernetes:
          role: webapp
          serviceAccount: demo-operator