global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'vault'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    scheme: https
    static_configs:
      - targets: ['vault-active.primary-vault.svc.cluster.local:8200']
    tls_config:
      ca_file: '/etc/prometheus/ca.crt'
      insecure_skip_verify: false
    authorization:
      credentials_file: '/etc/prometheus/prometheus-token'
