{
 "title": "Hashicorp Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(up{job=\"vault\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(up{job=\"vault\",instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": "label_values(vault_secret_kv_count, mount_point)"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"vault\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_secret_kv_count)",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(1 + vault_core_unsealed{})", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "CPU/Mem Info: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{} / vault_runtime_malloc_count{})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{})",
     "legendFormat": "$node"
    }
   ]
  },
  { "title": "Identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Active Clients Count (Current Month) Time-Series Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vault_identity_entity_active_partial_month",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Monthly Client Count Time-Series Graph (Reported Beginning of every Month)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vault_identity_entity_active_monthly",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Vault Clients Summary (Current Month)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "clients", "text": "Clients", "type": "number" },
      { "selector": "non_entity_clients", "text": "Non Entity Clients", "type": "number" },
      { "selector": "entity_clients", "text": "Entity Clients", "type": "number" },
      { "selector": "non_entity_tokens", "text": "Non Entity Tokens", "type": "number" },
      { "selector": "secret_syncs", "text": "Secret Sync Clients", "type": "number" },
      { "selector": "acme_clients", "text": "ACME Clients", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "data\n\n\n\n\n",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"data.total\"\n\n\n",
     "url": "https://vault.primary-vault.svc.cluster.local:8200/v1/sys/internal/counters/activity/monthly",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Active Clients Count (Current Month)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_identity_entity_active_partial_month",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entity Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_identity_num_entities", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Vault Clients Explorer",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "csv_options": {
      "skip_empty_lines": false
     },
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "uql": "parse-csv --delimiter \"\t\"",
     "url": "https://vault.primary-vault.svc.cluster.local:8200/v1/sys/internal/counters/activity/export",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "${__to:date:seconds}" },
       { "key": "format", "value": "csv" }
      ]
     }
    }
   ]
  },
  {
   "title": "Entities Alias Explorer",
   "type": "table",
   "gridPos": { "h": 17, "w": 14, "x": 0, "y": 49 },
   "targets": [
    {
     "csv_options": {
      "skip_empty_lines": false
     },
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "parser": "simple",
     "root_selector": "$.data.key_info.*",
     "source": "url",
     "type": "json",
     "uql": "parse-csv --delimiter \"\t\"",
     "url": "https://vault.primary-vault.svc.cluster.local:8200/v1/identity/entity-alias/id",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "header-key", "value": "header-value" }
      ],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "${__to:date:seconds}" },
       { "key": "list", "value": "true" }
      ]
     }
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 10, "x": 14, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(auth_method) (vault_identity_entity_alias_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entities Explorer",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 66 },
   "targets": [
    {
     "csv_options": {
      "skip_empty_lines": false
     },
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "parser": "simple",
     "root_selector": "$.data.key_info[*].*",
     "source": "url",
     "type": "json",
     "uql": "parse-csv --delimiter \"\t\"",
     "url": "https://vault.primary-vault.svc.cluster.local:8200/v1/identity/entity/id",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "header-key", "value": "header-value" }
      ],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "${__to:date:seconds}" },
       { "key": "list", "value": "true" }
      ]
     }
    }
   ]
  },
  {
   "title": "Entity Alias Count",
   "type": "stat",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(auth_method) (vault_identity_entity_alias_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault Entities Time Series Graph",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vault_identity_num_entities{}", "legendFormat": "GET" }
   ]
  },
  { "title": "VSO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "VSO Controllers Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "controller_resource_status", "legendFormat": "__auto" }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vault_token_count)" }
   ]
  },
  {
   "title": "Number of Tokens by Auth Mount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(auth_method) (vault_token_count_by_auth)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_create_count - vault_token_store_count)"
    }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_policy)",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_ttl)",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_auth)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 134 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_audit_log_request_count[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(vault_audit_log_response_count[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(vault_core_handle_request_count[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 139 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  }
 ]
}