### NAMESPACE NEEDS TO BE UPDATED ###

# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-neo4j-sync-config
  labels:
    app: vault-neo4j-sync
data:
  VAULT_URL: "https://vault.internal"
  NEO4J_URI: "bolt://neo4j.internal:7687"
  # Add any other non-sensitive configuration
---
# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vault-neo4j-sync-secrets
  labels:
    app: vault-neo4j-sync
type: Opaque
data:
  # Base64 encoded values - replace these with your actual encoded secrets
  VAULT_TOKEN: "${BASE64_ENCODED_VAULT_TOKEN}"
  NEO4J_USER: "${BASE64_ENCODED_NEO4J_USER}"
  NEO4J_PASSWORD: "${BASE64_ENCODED_NEO4J_PASSWORD}"
---
# cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-neo4j-sync
  labels:
    app: vault-neo4j-sync
spec:
  schedule: "*/30 * * * *"  # Runs every 30 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: vault-neo4j-sync
        spec:
          serviceAccountName: vault-neo4j-sync-sa
          containers:
          - name: sync
            image: vault-neo4j-sync:latest  # Replace with your image
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
            envFrom:
            - configMapRef:
                name: vault-neo4j-sync-config
            - secretRef:
                name: vault-neo4j-sync-secrets
          restartPolicy: OnFailure
---
# serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-neo4j-sync-sa
  labels:
    app: vault-neo4j-sync
---
# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-neo4j-sync-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-neo4j-sync-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-neo4j-sync-role
subjects:
- kind: ServiceAccount
  name: vault-neo4j-sync-sa