apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnaming-service
  namespace: hostnaming-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostnaming-service
  template:
    metadata:
      labels:
        app: hostnaming-service
    spec:
      volumes:
      - name: vault-ca-cert
        configMap:
          name: vault-ca-config  # Mount the CA from a ConfigMap
      containers:
      - name: hostnaming-service
        image: hostnaming-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: VAULT_ADDR
          value: "https://vault.primary-vault.svc.cluster.local:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-init-credentials
              key: root-token
---
apiVersion: v1
kind: Service
metadata:
  name: hostnaming-service
  namespace: hostnaming-service
spec:
  selector:
    app: hostnaming-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 32001
  type: NodePort